# Directories
ROOT_DIR = $$PWD
SRC_DIR = $$PWD/src
INCLUDEPATH += $$ROOT_DIR

LIBS += -larmadillo

# O3 optimization
release {
    DEFINES += ARMA_NO_DEBUG
    DEFINES += ARMA_USE_CXX11
    QMAKE_CXXFLAGS_RELEASE -= -O2
    QMAKE_CXXFLAGS_RELEASE += -O3
}

#C++11
COMMON_CXXFLAGS = -std=c++11
QMAKE_CXXFLAGS += $$COMMON_CXXFLAGS
QMAKE_CXXFLAGS_RELEASE += $$COMMON_CXXFLAGS
QMAKE_CXXFLAGS_DEBUG += $$COMMON_CXXFLAGS
